name: Pull from Shopify (DEV)

on:
  workflow_dispatch:  # Para ejecutarlo manualmente desde GitHub
  schedule:
    - cron: '*/5 * * * *' # Cada 5 minutos para prueba inmediata

permissions:
  contents: write

env:
  SHOPIFY_STORE_URL: radianz-store.myshopify.com
  THEME_DEV_ID: 152975179991

jobs:
  pull-dev:
    name: Pull Theme DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Pull from Shopify
        env:
          SHOPIFY_CLI_TOKEN: ${{ secrets.SHOPIFY_CLI_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ env.SHOPIFY_STORE_URL }}
        run: |
          echo "📥 Pulling theme from Shopify..."
          shopify theme pull \
            --theme ${{ env.THEME_DEV_ID }} \
            --store $SHOPIFY_FLAG_STORE \
            --password $SHOPIFY_CLI_TOKEN \
            --path . \
            --no-color

      - name: Check for Changes
        id: check_changes
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes detected from Shopify panel"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected from Shopify panel"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            git status --porcelain
          fi

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "shopify-sync-bot"
          git config user.email "shopify-bot@example.com"
          git add .
          git commit -m "📥 Sync from Shopify Theme DEV - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push origin dev
          echo "✅ Changes successfully synced from Shopify panel"

      - name: No Changes
        if: steps.check_changes.outputs.has_changes == 'false'
        run: |
          echo "ℹ️ No changes to sync - Shopify theme is already up to date"
